#!/usr/bin/bash

sh /opt/wcl/color
sh /opt/wcl/wcl-help-en
sh /opt/wcl/wcl-help-cn

############### Main of Wall Color ####################
wcl() {
if [[ $# ==  ]]











}

###wcl -pink "Hello, World!"